//
//  MoviesAppModels.swift
//  MovieApp
//
//  Created by Achem Samuel on 9/22/19.
//  Copyright (c) 2019 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UpcomingMovies
{
    struct ViewModel {
        var posterPaths : [MoviesViewModel] = []
    }
    
    enum FetchUpcomingMovies {
        struct Request {
            
        }
        
        struct Response {
            var upcomingMovies : [Movies]
        }
        
        struct ViewModel {
            var posterPaths : [MoviesViewModel]
        }
    }
}
