//
//  UpcomingMoviesPresenter.swift
//  MovieApp
//
//  Created by Achem Samuel on 9/22/19.
//  Copyright (c) 2019 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpcomingMoviesPresentationLogic
{
    func presentUpcomingMovies(response: UpcomingMovies.FetchUpcomingMovies.Response)
}
protocol UpcomingMoviesDisplayLogic: class
{
    func displayUpcomingMovies(viewModel: UpcomingMovies.FetchUpcomingMovies.ViewModel)
}
class UpcomingMoviesPresenter: UpcomingMoviesPresentationLogic
{
    
  weak var viewController: UpcomingMoviesDisplayLogic?
  
  func presentUpcomingMovies(response: UpcomingMovies.FetchUpcomingMovies.Response) {
    viewController?.displayUpcomingMovies(viewModel: UpcomingMovies.FetchUpcomingMovies.ViewModel(posterPaths: response.upcomingMovies.map({$0.toViewModel()})))
  }
  

}
